- name: Update package list
  apt:
    update_cache: true
  become: true

- name: Install PostgreSQL 16
  apt:
    name:
      - postgresql-16
      - postgresql-client-16
      - postgresql-contrib
    state: present
  become: true

- name: Stop PostgreSQL
  systemd:
    name: postgresql
    state: stopped
  become: true
  ignore_errors: true

- name: Remove old data
  file:
    path: "{{ data_root }}"
    state: absent
  become: true

- name: Create fresh data dir
  file:
    path: "{{ data_root }}"
    state: directory
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: '0700'
  become: true

- name: Run pg_basebackup from master
  command:
    cmd: >
      pg_basebackup -h 192.168.88.162 -U "{{ replica_user }}"
      -D "{{ data_root }}" -P -R -X stream
  become_user: "{{ pg_user }}"
  become: true
  environment:
    PGPASSWORD: "12345678"

- name: Create standby signal
  file:
    path: "{{ data_root }}/standby.signal"
    state: touch
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: '0600'
  become: true

- name: Start PostgreSQL
  systemd:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Create directory for logical replication instance
  file:
    path: "/pg_data/16-one-base"
    state: directory
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: '0700'
  become: true

- name: Initialize logical instance
  command:
    cmd: /usr/lib/postgresql/16/bin/initdb -D /pg_data/16-one-base -U postgres
  become_user: "{{ pg_user }}"
  become: true
  args:
    creates: "/pg_data/16-one-base/PG_VERSION"

- name: Set port for logical instance
  lineinfile:
    path: /pg_data/16-one-base/postgresql.conf
    line: "port = 5433"
    create: true
  become: true
  become_user: "{{ pg_user }}"

- name: Start logical instance
  shell: |
    /usr/lib/postgresql/16/bin/pg_ctl -D /pg_data/16-one-base start
  become_user: "{{ pg_user }}"
  become: true
  ignore_errors: true