[master]
ubuntu ansible_host=192.168.88.162 ansible_user=username ansible_password=12345678 ansible_become_password=12345678

[replica]
ubuntu ansible_host=192.168.88.172 ansible_user=pg-replica ansible_password=12345678 ansible_become_password=12345678