- name: prepare second postgres instance for logical replication
  hosts: replica
  become: true
  vars:
    logical_data_dir: /pg_data/16-one-base
    logical_port: 5544

  tasks:
    - name: create logical data directory
      ansible.builtin.file:
        path: "{{ logical_data_dir }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: install systemd unit for logical instance
      ansible.builtin.copy:
        dest: /etc/systemd/system/postgresql@16-logical.service
        mode: '0644'
        content: |
          [Unit]
          Description=PostgreSQL 16 logical instance
          After=network.target

          [Service]
          Type=forking
          User=postgres
          Group=postgres
          Environment=PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
          Environment=PG_OOM_ADJUST_VALUE=0
          Environment=PGDATA={{ logical_data_dir }}
          ExecStart=/usr/lib/postgresql/16/bin/pg_ctl start -D ${PGDATA} -l /var/log/postgresql/postgresql-16-logical.log -s -o "-c config_file=/etc/postgresql/16/logical/postgresql.conf"
          ExecStop=/usr/lib/postgresql/16/bin/pg_ctl stop -D ${PGDATA} -s -m fast
          ExecReload=/usr/lib/postgresql/16/bin/pg_ctl reload -D ${PGDATA} -s
          PIDFile=/var/run/postgresql/16-logical.pid
          Restart=on-failure
          RestartSec=5s

          [Install]
          WantedBy=multi-user.target

    - name: create configuration directory for logical instance
      ansible.builtin.file:
        path: /etc/postgresql/16/logical
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

    - name: reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: initialize logical cluster if not initialized
      ansible.builtin.command:
        cmd: /usr/lib/postgresql/16/bin/initdb -D {{ logical_data_dir }} --locale=C.UTF-8 --encoding=UTF8
      become_user: postgres
      args:
        creates: "{{ logical_data_dir }}/PG_VERSION"

    - name: copy default postgresql.conf to logical instance
      ansible.builtin.copy:
        src: /etc/postgresql/16/main/postgresql.conf
        dest: /etc/postgresql/16/logical/postgresql.conf
        remote_src: yes
        owner: postgres
        group: postgres
        mode: '0644'

    - name: set logical instance port
      ansible.builtin.lineinfile:
        path: /etc/postgresql/16/logical/postgresql.conf
        regexp: '^#?port\s*='
        line: "port = {{ logical_port }}"

    - name: set logical instance listen addresses
      ansible.builtin.lineinfile:
        path: /etc/postgresql/16/logical/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '*'"

    - name: set logical instance data directory
      ansible.builtin.lineinfile:
        path: /etc/postgresql/16/logical/postgresql.conf
        regexp: '^#?data_directory\s*='
        line: "data_directory = '{{ logical_data_dir }}'"

    - name: create pg_hba.conf for logical instance
      ansible.builtin.copy:
        dest: /etc/postgresql/16/logical/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '0640'
        content: |
          local   all             postgres                                peer
          local   all             all                                     peer
          host    all             all             127.0.0.1/32            scram-sha-256
          host    all             all             ::1/128                 scram-sha-256
          host    replication     all             192.168.88.0/24         scram-sha-256
          host    all             all             192.168.88.0/24         scram-sha-256

    - name: create symlink for postgresql.conf
      ansible.builtin.file:
        src: /etc/postgresql/16/logical/postgresql.conf
        dest: "{{ logical_data_dir }}/postgresql.conf"
        state: link
        owner: postgres
        group: postgres
        force: yes

    - name: create symlink for pg_hba.conf
      ansible.builtin.file:
        src: /etc/postgresql/16/logical/pg_hba.conf
        dest: "{{ logical_data_dir }}/pg_hba.conf"
        state: link
        owner: postgres
        group: postgres
        force: yes

    - name: enable and start logical instance service
      ansible.builtin.systemd:
        name: postgresql@16-logical.service
        enabled: true
        state: started

    - name: wait for logical instance to start
      ansible.builtin.wait_for:
        port: "{{ logical_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        delay: 5
        timeout: 30

    - name: verify logical instance is running
      ansible.builtin.command:
        cmd: /usr/lib/postgresql/16/bin/pg_isready -p {{ logical_port }}
      register: pg_status
      changed_when: false