- name: prepare replica postgresql host
  hosts: replica
  become: true
  vars:
    postgres_packages:
      - postgresql-16
      - postgresql-client-16
      - postgresql-contrib-16
      - python3-psycopg2

  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
      ignore_errors: yes

    - name: install postgresql packages
      ansible.builtin.apt:
        name: "{{ postgres_packages }}"
        state: present

    - name: create pg_data directory
      ansible.builtin.file:
        path: /pg_data
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: stop postgresql service
      ansible.builtin.systemd:
        name: postgresql
        state: stopped
        enabled: true

    - name: drop default cluster if exists
      ansible.builtin.command:
        cmd: pg_dropcluster --stop 16 main
      register: drop_cluster
      changed_when: drop_cluster.rc == 0
      failed_when: drop_cluster.rc not in [0, 1]